### ISSUE TITLE
SyntaxError: Non-default export is not supported in main.js:20

### ISSUE THREAD

**Issue by duffn** [jirutka/njs-typescript-starter#1]
Hello,
Thank you for the nice starter. I'm attempting to run the project and after having installed dependencies and building, receive this error when running `npm run start`.
Thanks for any help.

```
$ npm -v
7.13.0
```
```
$ node -v
v16.2.0
```

```
$ npm run start

> njs-typescript-starter@0.0.0 start
> run-p watch start-nginx


> njs-typescript-starter@0.0.0 watch
> rollup -c --watch --no-watch.clearScreen


> njs-typescript-starter@0.0.0 start-nginx
> start-nginx --version 1.19.x --port 8090 --watch dist/ integration-tests/nginx.conf

rollup v2.58.0
bundles src/index.ts → dist/main.js...
nginx-binaries: Downloading https://jirutka.github.io/nginx-binaries/nginx-1.19.10-x86_64-darwin...
created dist/main.js in 280ms

[2021-10-02 13:42:42] waiting for changes...
nginx-testing: Starting nginx 1.19.10 on port(s): 8090
2021/10/02 13:42:42 [warn] 2989#1792475: the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /Users/duffy/code/njs-typescript-starter/integration-tests/.nginx.conf~:10
2021/10/02 13:42:42 [emerg] 2989#1792475: SyntaxError: Non-default export is not supported in main.js:20
nginx-testing: Failed to start nginx, no response on port 8090
ERROR: "start-nginx" exited with 1.
```

My main.js file is generated like this:

```js

/*!
* ${njs-typescript-starter} ${a56bd527ed489308c512e11f71a747a846f00686}
* 
* Date: 2021-10-02
* */
import qs from 'querystring';

function hello(r) {
  var name = r.args.name ? qs.unescape(r.args.name) : 'world';
  return r.return(200, `
    Meow, ${name}!

        ("\`-''-/").___..--''"\`-._
        \`6_ 6  )   \`-.  (     ).\`-.__.\`)
        (_Y_.)'  ._   )  \`._ \`. \`\`-..-'
      _..\`--'_..-_/  /--'_.' ,'
      (il),-''  (li),'  ((!.-'
  `);
}

var index = {
  hello
};

export { index as default };
```

**Comment by jirutka** [comment]
What exactly don’t you understand on the error message: `SyntaxError: Non-default export is not supported in main.js:20`?
It’s even mentioned in [src/index.ts](https://github.com/jirutka/njs-typescript-starter/blob/master/src/index.ts).

EDIT: Aha, I see now, you just built the example and it produces `export { index as default };`.

**Comment by duffn** [comment]
The starter is meant to generate a non-working project per the README instructions? All I've done is clone the project and attempt to run it per the README.

EDIT: Yes, I've only built the example.

**Comment by jirutka** [comment]
No, it’s not. I misunderstood your report. Sorry about it.

**Comment by jirutka** [comment]
This regression is caused by changes in [rollup 2.55.0](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#2550), specifically [#4182](https://github.com/rollup/rollup/pull/4182).
