### ISSUE TITLE
async/await support added to njs

### ISSUE THREAD

**Issue by joh-klein** [jirutka/njs-typescript-starter#2]
Hi,
I really appreciate this starter repo – it helped me a lot. After I got everything working months ago I had a look at it again today for some maintenance. I updated the stable nginx from 1.18.0 to 1.20.2 and saw, that njs now supports async/await (since v0.7.0) … 

I looked around to see, what would need to change. But since there are quite a couple of things running and compiling etc I came here to ask for your help :)

**Comment by jirutka** [comment]
I just updated all dependencies and settings. I’m sorry for such a late reply.
